Update deploy-iac-template.yaml

diff --git a/.github/workflows/deploy-iac-template.yaml b/.github/workflows/deploy-iac-template.yaml
--- a/.github/workflows/deploy-iac-template.yaml
+++ b/.github/workflows/deploy-iac-template.yaml
@@ -77,9 +77,9 @@ jobs:
         terraform plan -no-color -input=false
       continue-on-error: true
 
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
 
     - name: Terraform Apply
       run: |
